#定义基础镜像
FROM {harbor}/{repository}/rust-builder AS build

WORKDIR /work
#拷贝源代码
COPY .. .
ENV TFLITE_LIB_DIR=/work/tflite-rs/submodules/deps/

RUN cargo build --release --quiet --bin tts_server

FROM ubuntu:20.04

ENV TZ=Asia/Shanghai
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ARG USER=tts
ARG USERPWD=tts

RUN sed -i s@archive.ubuntu.com@mirrors.aliyun.com@g /etc/apt/sources.list
RUN apt-get clean
RUN apt-get update --fix-missing
RUN apt-get install -y tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata
RUN apt-get install -y apt-utils pkg-config openssl libssl-dev curl
RUN apt-get install -y net-tools vim strace

RUN apt-get install -y sudo
RUN adduser --ingroup sudo --disabled-password --gecos "" --shell /bin/bash --home /home/${USER} ${USER} && \
    usermod -aG sudo ${USER} && \
    echo "%sudo  ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd
RUN echo "$USER:$USERPWD" | chpasswd

RUN sed -i s@security.ubuntu.com@mirrors.aliyun.com@g /etc/apt/sources.list

WORKDIR /work/

COPY ./assets /work/assets
COPY ./demo /work/demo
COPY ./config /work/config
COPY ./docker/bin /work
COPY ./tflite-rs/submodules/deps/libtensorflowlite.so /work
COPY --from=build /work/target/release/tts_server /work/

#定义环境变量
ENV PATH=/work:$PATH

EXPOSE 40004
CMD ["bash", "/work/start.sh"]
