version: '3'
services:
  tts_server:
    image: harbor.cowarobot.cn/voyance/tts_server:20240112
    restart: always
    ports:
      - "40000:40004"
    volumes:
      - ./logs:/work/logs
    networks:
      tts:
        ipv4_address: 10.10.1.11
    restart: always

networks:
  tts:
    external: false
    name: tts_network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/16
          gateway: 10.10.1.1
